services:
  tilemap-server:
    build: .
    image: ghcr.io/teochenglim/mapwatch-py/tilemap-server:${IMAGE_TAG:-latest}
    ports:
      - "8001:80"
    environment:
      BASE_URL: "${BASE_URL:-http://localhost:8000}"
      ROOT_PATH: /department/tilemap-server
    volumes:
      - ./tiles:/tiles:ro
    restart: unless-stopped
